#!/bin/sh
ODIR=`pwd`/frozen
cd src
DIRS=`find  -iname '*.py' | xargs dirname | sort -u`
FILES=`find -iname '*.py'`

for x in ${DIRS}
do
      mkdir -p ${ODIR}/$x
done

for x in ${FILES}
do
	y=`echo $x | sed -e 's/.py/.mpy/'`
	mpy-cross -march=xtensa -o ${ODIR}/$y  $x 
done

for x in boot.py main.py passive.py
do
	cp $x ${ODIR}/$x
done
